"""Committed deployed-default artifacts (a stable, precomputed reference).

The hosted backend can serve a stable committed result without re-scoring by
reading :func:`load_reference`, which returns the precomputed
``reference.json``: the deployed-default summary plus the known-CAR-recovery and
the pure-noise honest-null numbers.

The artifact is generated by ``scripts/build_reference.py`` from the seeded
synthetic panel, so it is fully reproducible. Importing this module has no side
effects (the JSON is read only when :func:`load_reference` is called).
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources
from typing import Any

#: The committed reference artifact filename (precomputed deployed default).
REFERENCE_FILENAME: str = "reference.json"


@lru_cache(maxsize=1)
def load_reference() -> dict[str, Any]:
    """Return the committed deployed-default reference as a plain ``dict``.

    Reads the packaged ``reference.json`` via :mod:`importlib.resources` (so it
    works from a wheel as well as a source checkout) and caches the parsed
    mapping. The mapping holds the deployed-default ``summary``, the
    ``known_car_recovery`` block, and the ``pure_noise_honest_null`` block.

    Returns
    -------
    dict[str, Any]
        The parsed reference artifact.

    Raises
    ------
    FileNotFoundError
        If the artifact is missing from the package (a broken build).
    """
    resource = resources.files(__package__).joinpath(REFERENCE_FILENAME)
    with resources.as_file(resource) as path:
        text = path.read_text(encoding="utf-8")
    payload: dict[str, Any] = json.loads(text)
    return payload
